[package]
name = "gen_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17.1", features = ["wgpu", "train", "vision"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.17"
